#!/usr/bin/env python
import signal
import argparse
import subprocess
import os
import time
import ConfigParser

signal.signal(signal.SIGCHLD, signal.SIG_IGN)
config = ConfigParser.RawConfigParser()
config.read('test-suite.cfg')
dev = config.get('interface', 'dev')
ip = config.get('interface', 'ip')
essid = config.get('interface', 'essid')
dumpfile = config.get('iofiles', 'dumpfile')
clickfile = config.get('iofiles', 'clickfile')
series = config.getint('test', 'series')
sendsperseries = config.getint('test', 'sendsperseries')
firstorsecond = config.get('test', 'firstorsecond')
runname = config.get('test', 'runname')

parser = argparse.ArgumentParser(prog="dxwifi",
    description="DxWifi Test-Suite")

parser.add_argument("-n", "--networkmanager",
    action="store_true", required=False,
    help="Restarts network manager")

parser.add_argument("-f", "--file",
    action="store_true", required=False,
    help="Writes recieved packets to .pcap or .txt file")

parser.add_argument("-l", "--listen",
    action="store_true", required=False,
    help="Writes recieved packets to stdout")

parser.add_argument("-c", "--click", metavar="FILE.click", action="store",
    required=False, help="Specify a .click file to load")

parser.add_argument("-t", "--transmit",
    action="store_true", required=False,
    help="Installs .click file from .cfg")

parser.add_argument("-a", "--automate",
    action="store_true", required=False,
    help="Automates sending and recieving")

parser.add_argument("-s", "--stopclick",
    action="store_true", required=False,
    help="Uninstalls click")

args = vars(parser.parse_args())

def test_click():
    try:
        click = subprocess.check_output(["click", "--version"])
    except:
        exit("You must have click installed, or else.")

def test_root():
    if os.getuid() != 0:
        exit("You must have root privileges, or else.")

def set_internet():
    stopclick()
    subprocess.call(["start", "network-manager"])

def stopclick():
    subprocess.call(["click-uninstall"])

def card_down():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " +  "ifconfig", dev, "down"
    subprocess.call(["ifconfig", dev, "down"])
        
def card_up():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " +  "ifconfig", dev, "down"
    subprocess.call(["ifconfig", dev, "up"])
    
def click_config():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " + "card_down()"
    card_down()

    try:
        print str(int(time.time()) % 60) + ": " +  "iwconfig", dev, "mode", "ad-hoc", "essid", essid
        subprocess.call(["iwconfig", dev, "mode",
            "ad-hoc", "essid", essid])
    except:
        exit()

    try:
        print str(int(time.time()) % 60) + ": " +  "ifconfig", dev, ip
        subprocess.call(["ifconfig", dev, ip])
    except:
        exit()

    print str(int(time.time()) % 60) + ": " + "sleep(10)"
    time.sleep(10)

def delta_time(nearest):
    while(int(time.time()) % nearest):
        time.sleep(1)
    return

def auto():
    for y in range(0, series):
        try:
            os.mkdir("./" + runname + "/" + firstorsecond + "_series" + str(y))
        except:
            pass

        while(int(time.time()) % 10 != 0):
            time.sleep(1)

        try:
            os.mkdir("./" + runname)
        except:
            pass

 
        series_dir = "./" + runname + "/" + firstorsecond + "_series" + str(y) + "/"
        for x in range(0, sendsperseries):
            if firstorsecond == "first":
                if(x == 0):
                    print str(int(time.time()) % 60) + ": " +  "click_config()"
                    click_config()
                    print str(int(time.time()) % 60) + ": " + "sleep(20)"
                    delta_time(20)
                print str(int(time.time()) % 60) + ": " + "sleep(12)"
                time.sleep(2)
                print str(int(time.time()) % 60) + ": " + "transmit()"
                transmit()
                print str(int(time.time()) % 60) + ": " + "sleep(13)"
                time.sleep(13)
                print str(int(time.time()) % 60) + ": " + "delta_time(20)"
                delta_time(20)

            if firstorsecond == "second":
                if(x == 0):
                    print str(int(time.time()) % 60) + ": " +  "listen_config()"
                    listen_config()
                    print str(int(time.time()) % 60) + ": " + "sleep(10)"
                    time.sleep(10)
                    delta_time(20)
                to_write = series_dir + "test" + str(x) + ".pcap"
                print str(int(time.time()) % 60) + ": " +  "tcpdump", "-ennvvKXXSi", dev, "port", "12121", "-w", to_write
                tcpdmp = subprocess.Popen(["tcpdump", "-ennvvvKXXSi", dev,
                "port 12121", "-w", to_write])
                print str(int(time.time()) % 60) + ": " + "sleep(15)"
                time.sleep(15)
                print str(int(time.time()) % 60) + ": " + "kill(tcpdmp)"
                subprocess.Popen.kill(tcpdmp)
                print str(int(time.time()) % 60) + ": " + "sleep(20)"
                delta_time(20)

        for x in range(0, sendsperseries):
            if firstorsecond == "second":
                if(x == 0):
                    print str(int(time.time()) % 60) + ": " +  "click_config()"
                    click_config()
                    print str(int(time.time()) % 60) + ": " + "delta_time(20)"
                    delta_time(20)
                print str(int(time.time()) % 60) + ": " + "sleep(2)"
                time.sleep(2)
                print str(int(time.time()) % 60) + ": " + "transmit()"
                transmit()
                print str(int(time.time()) % 60) + ": " + "sleep(13)"
                time.sleep(13)
                print str(int(time.time()) % 60) + ": " + "sleep(20)"
                delta_time(20)

            if firstorsecond == "first":
                if(x == 0):
                    print str(int(time.time()) % 60) + ": " + "listen_config()"
                    listen_config()
                    print str(int(time.time()) % 60) + ": " + "sleep(10)"
                    time.sleep(10)
                    print str(int(time.time()) % 60) + ": " + "delta_time(20)"
                    delta_time(20)
                to_write = series_dir + "test" + str(x) + ".pcap"
                print str(int(time.time()) % 60) + ": " +  "tcpdump", "-ennvvKXXSi", dev, "port", "12121", "-w", to_write
                tcpdmp = subprocess.Popen(["tcpdump", "-ennvvvKXXSi", dev,
                "port 12121", "-w", to_write])
                print str(int(time.time()) % 60) + ": " + "sleep(15)"
                time.sleep(15)
                print str(int(time.time()) % 60) + ": " + "kill(tcpdmp)"
                subprocess.Popen.kill(tcpdmp)
                print str(int(time.time()) % 60) + ": " + "delta_time(20)"
                delta_time(20)

def set_click():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " +  "click-install", args["click"]
    subprocess.call(["click-install", args["click"]])

def transmit():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " +  "click-install", clickfile
    to_install = "./" + clickfile
    subprocess.call(["click-install", to_install])

def listen_config():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()
    print str(int(time.time()) % 60) + ": " +  "stop network-manager"
    subprocess.call(["stop", "network-manager"])
    print str(int(time.time()) % 60) + ": " +  "card_down()"
    card_down()
    print str(int(time.time()) % 60) + ": " +  "iwconfig", dev, "mode", "monitor"
    subprocess.call(["iwconfig", dev, "mode", "monitor"])
    print str(int(time.time()) % 60) + ": " +  "card_up()"
    card_up()
    print str(int(time.time()) % 60) + ": " +  "iwconfig", dev, "channel", "2.412"
    subprocess.call(["iwconfig", dev, "channel", "2.412"])
    
def set_listen():
    print str(int(time.time()) % 60) + ": " +  "stopclick()"
    stopclick()

    print str(int(time.time()) % 60) + ": " +  "tcpdump", "-enntKXXSi", dev, "port", "12121"
    tcpdmp = subprocess.call(["tcpdump", "-enntKXXSi", dev,
    "port", "12121"])


def infile():
    stopclick()

    if dumpfile.endswith(".pcap"):
        subprocess.call(["tcpdump", "-ennvvvKXXSi", dev, 
        "port", "12121", "-w", "./" + dumpfile])
    elif dumpfile.endswith(".txt"):
        subprocess.call(["tcpdump", "-ennvvvKXXSi", dev,
        "port", "12121", ">", "./" + dumpfile])

if __name__ == "__main__":
    test_click()
    test_root()

    if args["stopclick"]:
        stopclick()

    elif args["networkmanager"]:
        set_internet()

    elif args["listen"]:
        subprocess.call(["stop", "network-manager"])
        listen_config()
        set_listen()

    elif args["file"]:
        subprocess.call(["stop", "network-manager"])
        listen_config()
        infile()

    elif args["transmit"]:
        subprocess.call(["stop", "network-manager"])
        click_config()
        transmit()

    elif args.get("automate"):
        subprocess.call(["stop", "network-manager"])
        auto()

    elif args.get("click") is not None:
        subprocess.call(["stop", "network-manager"])
        click_config()
        set_click()
    
    else:
        print "Please specify a valid argument, see --help"

